# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# the build will trigger on any changes to the master branch
trigger:
- develop

# the build will run on a Microsoft hosted agent, using the lastest Windows VM Image
pool:
  vmImage: 'windows-latest'

# these variables are available throughout the build file
# just the build configuration is defined, in this case we are building Release packages
variables:
  buildConfiguration: 'Debug'

#The build has 3 seperate tasks run under 1 step
steps:

# The first task is the dotnet command build, pointing to our csproj file
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'src/SereneApi.Extensions.Newtonsoft/SereneApi.Extensions.Newtonsoft.csproj'
    
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: 'tests/SereneApi.Extensions.Newtonsoft.Tests/SereneApi.Extensions.Newtonsoft.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
